### PR TITLE
Mention SPDX in README

### PR DESCRIPTION
**Pull request by tripu**

### CODE REVIEW

**Comment by tripu** [comment]
@wseltzer, what do you think?

**Comment by tripu** [comment]
I guess you don't like having that reference to SPDX and software licences on the README, @wseltzer&hellip;?

**Comment by wseltzer** [comment]
@tripu not if it's the wrong license. We use the W3C Software License

**Comment by tripu** [comment]
The PR is not imposing any licence, only explaining how to include that information on a W3C repo.
For software repositories we are using the MIT licence in most cases, I think.

**Comment by tripu** [comment]
Closing it, since it's not going anywhere.

**Pull request closed without merging**
